export default () => ({
  authenticate: false,
  Users: null,
  menu: null,
  languages: ["Español", "Català", "English"],
  languageSelected: 0,
  isLogged: false,
  products: [],
  families: [],
  familyId: null,
  ptypes: [],
  ptypeId: null,
  departments: [],
  token: null,
  userLogged: {},
  user: {},
});
